on: [push] 
# 1. DÉCLENCHEUR : Dès que je pousse du code sur GitHub...

jobs:
  test-api:
    runs-on: ubuntu-latest
    # 2. MACHINE : Ouvre un ordinateur virtuel sous Linux (Ubuntu).

    steps:
      - uses: actions/checkout@v4
      # 3. ÉTAPE 1 : Télécharge mes fichiers de projet sur cet ordinateur.

      - uses: actions/setup-node@v4
      # 4. ÉTAPE 2 : Installe le moteur Node.js.

      - run: npm install -g newman
      # 5. ÉTAPE 3 : Installe l'outil Newman dans le terminal.

      - run: newman run Platzi_...json -e Dev_...json
      # 6. ÉTAPE 4 : Lance mes tests Postman et affiche le résultat !
